user_update_email_confirm:
    path: /confirm-email-update/{token}/{redirectRoute}
    controller: Azine\EmailUpdateConfirmationBundle\Controller\ConfirmEmailUpdateController::confirmEmailUpdateAction
    methods: [GET]
